django_blog/blog/urls.py
from django.urls import path
from blog import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'blog'

urlpatterns = [
    path('', views.IndexView.as_view(), name='main-page'),
    path('section/<section>/', views.IndexView.as_view(), name='section'),
    path('section/<section>/post/<slug>', views.PostView.as_view(), name='section-post'),
    path('post/<slug>', views.PostView.as_view(), name='post'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('post/', views.PostCreateView.as_view(), name='post-create'),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django_blog/django_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
]

django_blog/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify

from blog.querysets import BlogSectionQS


class BlogSection(models.Model):
    name = models.CharField(max_length=100, verbose_name='Раздел блога')
    slug = models.SlugField(
        verbose_name='Название раздела в ссылке',
        unique=True,
        allow_unicode=True
    )
    # добавить views_per_day по разделу позже и сделать миграцию данных, которая заполнит значения
    # views_per_day = models.PositiveIntegerField(
    #     verbose_name='Количество просмотров постов раздела в день'
    # )

    objects = BlogSectionQS.as_manager()

    def __str__(self):
        return f'{self.name}'


class BlogPost(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название публикации')
    author = models.ForeignKey(User, on_delete=models.DO_NOTHING, verbose_name='Создатель поста')
    text = models.TextField(verbose_name='Текст поста')
    slug = models.SlugField(verbose_name='Название поста в ссылке', allow_unicode=True, unique=True)
    short_description = models.CharField(
        max_length=100,
        null=True,
        blank=True,
        verbose_name='Краткое содержание поста'
    )
    sections = models.ManyToManyField(
        BlogSection,
        verbose_name='Разделы, в которых опубликован пост',
        related_name='relate_posts'
    )
    view_count = models.PositiveIntegerField(default=0, verbose_name='Количество просмотров поста')


    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if not self.slug:
            self.slug = slugify(self.name)

        super().save(force_insert, force_update, using, update_fields)

    def __str__(self):
        return f'{self.name} | {self.author.username}'


class Tag(models.Model):
    name = models.CharField(max_length=20)

django_blog/blog/forms.py
from django import forms


def validate_password(value):
    if value in {'password', '123456789', '987654321'}:
        raise forms.ValidationError(
            'Пароль слишком простой!', code='invalid',
        )


class SignupForm(forms.Form):
    username = forms.CharField(max_length=150, required=True)
    email = forms.EmailField(required=True)
    # добавить валидаторы пароля
    password = forms.CharField(
        min_length=8,
        max_length=128,
        widget=forms.PasswordInput(),
        required=True,
        validators=[validate_password]
    )


class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=128, widget=forms.PasswordInput())

django_blog/blog/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth import views as auth_views
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import generic
from django.db import transaction
from blog.forms import SignupForm, LoginForm
from blog.models import BlogPost, BlogSection


class IndexView(generic.TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user

        section_slug = self.kwargs.get('section')

        if section_slug:
            section = BlogSection.objects.get(slug='auto')
            blog_posts = section.related_posts.all()
        else:
            blog_posts = BlogPost.objects.all()
            
        
        context['blog_posts'] = blog_posts
        
        return context


# 1 Iteration
# https://docs.djangoproject.com/en/3.1/ref/class-based-views/base/#view
# class SignupView(generic.View):
#     def get(self, request, *args, **kwargs):
#         form = SignupForm()
#         context = {'user': request.user, 'form': form}
#         return render(request, 'signup.html', context)
#
#     def post(self, request, *args, **kwargs):
#         form = SignupForm(request.POST)
#
#         if form.is_valid():
#             with transaction.atomic():
#                 user = User.objects.create_user(
#                     username=form.cleaned_data.get('username'),
#                     email=form.cleaned_data.get('email'),
#                     password=form.cleaned_data.get('password'),
#                 )
#
#             login(request, user)
#
#             return HttpResponseRedirect(reverse('blog:main-page'))
#         else:
#             context = {'user': request.user, 'form': form}
#             return render(request, 'signup.html', context)

        
class SignupView(generic.FormView):
    template_name = 'signup.html'
    form_class = SignupForm

    def form_valid(self, form):
        with transaction.atomic():
            user = User.objects.create_user(
                username=form.cleaned_data.get('username'),
                email=form.cleaned_data.get('email'),
                password=form.cleaned_data.get('password'),
            )

        login(self.request, user)

        return HttpResponseRedirect(reverse('blog:main-page'))


# https://docs.djangoproject.com/en/3.1/ref/class-based-views/generic-editing/#createview
class PostCreateView(generic.CreateView):
    template_name = 'blogpost_form.html'
    model = BlogPost
    fields = ['name', 'author', 'slug', 'text', 'short_description', 'sections']

    def get_success_url(self):
        return reverse('blog:post', kwargs={'slug': self.object.slug})


# https://docs.djangoproject.com/en/3.1/ref/class-based-views/generic-display/#detailview
class PostView(generic.DetailView):
    model = BlogPost
    template_name = 'blogpost.html'
    context_object_name = 'blog_post'


# 1 iteration
class LoginView(generic.FormView):
    form_class = LoginForm
    template_name = 'login.html'

    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        print(f'{username=} {password=}')
        user = authenticate(username=username, password=password)

        if user is not None:
            login(self.request, user)
            return redirect('blog:main-page')

        return self.form_invalid(form)

    def form_invalid(self, form):
        return self.render_to_response(
            self.get_context_data
            (
                form=form,
                is_login_or_password_invalid=True,
            )
        )

# 2  Iteration
# # https://docs.djangoproject.com/en/3.1/topics/auth/default/#django.contrib.auth.views.LoginView
# class LoginView(auth_views.LoginView):
#     template_name = 'login.html'
#     authentication_form = LoginForm


class LogoutView(auth_views.LogoutView):
    next_page = 'blog:main-page'
    

django_blog/blog/templates/blogpost.html
{% extends 'index.html' %}

{% block content %}
    <h1>{{ blog_post.name }}</h1>
    {% if blog_post.short_description %}
        <h2>{{ blog_post.short_description }}</h2>
    {% endif %}
    <p>{{ blog_post.text }}</p>
    <p>Автор: {{ blog_post.author.username }}</p>
{% endblock %}

django_blog/blog/templates/blogpost_form.html
{% extends 'index.html' %}

{% block content %}
    <h1>Новый пост</h1>
    <form action="{% url 'blog:post-create' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Создать">
    </form>
{% endblock %}

django_blog/blog/templates/index.html
{% load static %}
<html>
    <head>
        <title>Django Blog</title>
        <link rel="stylesheet" href="{% static 'css/awsm_theme.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
    </head>
    <body>
        <header>
        {% if user.is_authenticated %}
            <span>Добро пожаловать, {{ user.username }}.</span>
            <a id="logout" class="pull-right" href="{% url 'blog:logout' %}">Выход</a>
        {% else %}
            <p><a href="{% url 'blog:signup' %}">Регистрация</a></p>
            <p><a href="{% url 'blog:login' %}">Вход</a></p>
        {% endif %}
        </header>

        {% block navigation %}
        <nav>
            <a href="{% url 'blog:main-page' %}">Главная</a>
            {% if top_sections %}
                {% for blog_section in top_sections %}
                    <a href="{% url 'blog:section' blog_section.slug %}">blog_section.name</a>
                {% endfor %}
            {% endif %}
            {% if user.is_authenticated and user.is_staff %}
                <a href="{% url 'blog:post-create' %}">Создать пост</a>
            {% endif %}
        </nav>
        {% endblock %}

        {% block content %}

        <section>
            {% for blog_post in blog_posts %}
                <div class="blog-post">
                    <p><a href="{% url 'blog:post' blog_post.slug %}"> {{ blog_post.name }}</a></p>
                    <p> {{ blog_post.announce }} </p>
                </div>
            {% empty %}
                <p>Посты отсуствуют</p>
            {% endfor %}
        </section>

        {% endblock  %}
    </body>
</html>

django_blog/blog/templates/login.html
{% extends 'index.html' %}
{% block content %}
    <div class="centered">
        <p>Войти</p>
        <form action="{% url 'blog:login' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            {% if is_login_or_password_invalid %}
            <p class="error">Неправильный логин или пароль</p>
            {% endif %}
            <input type="submit" value="Вход">
        </form>
    </div>
{% endblock %}

django_blog/blog/templates/signup.html
{% extends 'index.html' %}
{% block content %}
    <div class="centered">
        <form action="{% url 'blog:signup' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Готово">
        </form>
    </div>
{% endblock %}